- CHANGELOG.md
- src/main/scala/sangria/ast/AstVisitor.scala
- src/main/scala/sangria/ast/QueryAst.scala
- src/main/scala/sangria/execution/Executor.scala
- src/main/scala/sangria/execution/ResultResolver.scala
- src/main/scala/sangria/introspection/package.scala
- src/main/scala/sangria/macros/AstLiftable.scala
- src/main/scala/sangria/parser/QueryParser.scala
- src/main/scala/sangria/renderer/QueryRenderer.scala
- src/main/scala/sangria/renderer/SchemaRenderer.scala
- src/main/scala/sangria/schema/Context.scala
- src/main/scala/sangria/schema/Schema.scala
- src/main/scala/sangria/schema/package.scala
- src/main/scala/sangria/util/StringUtil.scala
- src/main/scala/sangria/validation/Violation.scala
- src/main/scala/sangria/validation/rules/KnownDirectives.scala
- src/main/scala/sangria/validation/rules/KnownTypeNames.scala
- src/test/resources/queries/schema-kitchen-sink.graphql
- src/test/scala/sangria/execution/ExecutorSpec.scala
- src/test/scala/sangria/introspection/IntrospectionSpec.scala
- src/test/scala/sangria/macros/LiteralMacroSpec.scala
- src/test/scala/sangria/parser/QueryParserSpec.scala
- src/test/scala/sangria/parser/SchemaParserSpec.scala
- src/test/scala/sangria/renderer/QueryRendererSpec.scala
- src/test/scala/sangria/renderer/SchemaRenderSpec.scala
- src/test/scala/sangria/util/ValidationSupport.scala
- src/test/scala/sangria/validation/rules/KnownDirectivesSpec.scala
> IDL (schema definition) syntax parsing and rendering

- src/main/scala/sangria/schema/AstSchemaBuilder.scala
- src/main/scala/sangria/schema/AstSchemaMaterializer.scala
- src/main/scala/sangria/schema/IntrospectionSchemaBuilder.scala
- src/main/scala/sangria/schema/IntrospectionSchemaMaterializer.scala
- src/main/scala/sangria/schema/Schema.scala
- src/test/scala/sangria/schema/AstSchemaMaterializerSpec.scala
- src/test/scala/sangria/schema/SchemaExtensionSpec.scala
- src/test/scala/sangria/util/CatsSupport.scala
> Extend schema

- src/main/scala/sangria/ast/AstVisitor.scala
- src/main/scala/sangria/ast/QueryAst.scala
- src/main/scala/sangria/execution/FieldCollector.scala
- src/main/scala/sangria/macros/AstLiftable.scala
- src/main/scala/sangria/parser/QueryParser.scala
- src/main/scala/sangria/renderer/QueryRenderer.scala
- src/main/scala/sangria/renderer/SchemaRenderer.scala
- src/main/scala/sangria/schema/AstSchemaBuilder.scala
- src/main/scala/sangria/validation/QueryValidator.scala
- src/main/scala/sangria/validation/rules/FieldsOnCorrectType.scala
- src/main/scala/sangria/validation/rules/FragmentsOnCompositeType.scala
- src/main/scala/sangria/validation/rules/LoneAnonymousOperation.scala
- src/main/scala/sangria/validation/rules/NoFragmentCycles.scala
- src/main/scala/sangria/validation/rules/NoUnusedFragments.scala
- src/main/scala/sangria/validation/rules/ProvidedNonNullArguments.scala
- src/main/scala/sangria/validation/rules/ScalarLeafs.scala
- src/main/scala/sangria/validation/rules/UniqueOperationNames.scala
- src/test/scala/sangria/macros/LiteralMacroSpec.scala
- src/test/scala/sangria/parser/QueryParserSpec.scala
- src/test/scala/sangria/parser/SchemaParserSpec.scala
- src/test/scala/sangria/renderer/QueryRendererSpec.scala
- src/test/scala/sangria/renderer/SchemaRenderSpec.scala
- src/test/scala/sangria/schema/AstSchemaMaterializerSpec.scala
- src/test/scala/sangria/util/DebugUtil.scala
Ref #155 
Also more comments are now parsed and rendered (trailing comments, for instance).
> Update description formatting/parsing based in the changes in the reference implementation

- src/main/scala/sangria/ast/QueryAst.scala
- src/main/scala/sangria/schema/Schema.scala
- src/main/scala/sangria/schema/SchemaComparator.scala
- src/test/scala/sangria/schema/SchemaComparatorSpec.scala
> Schema comparator

- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/sangria/execution/ExecutionPath.scala
- src/main/scala/sangria/execution/Executor.scala
- src/main/scala/sangria/execution/Resolver.scala
- src/main/scala/sangria/macros/derive/DeriveInputObjectTypeMacro.scala
- src/main/scala/sangria/macros/derive/DeriveObjectTypeMacro.scala
- src/main/scala/sangria/validation/QueryValidator.scala
- src/test/scala/sangria/execution/ExecutorSpec.scala
- src/test/scala/sangria/schema/CoercionSpec.scala
- src/test/scala/sangria/streaming/StreamSpec.scala
- src/test/scala/sangria/util/DebugUtil.scala
> Scala 2.12

- src/main/scala/sangria/execution/deferred/DeferredResolver.scala
- src/main/scala/sangria/execution/deferred/Fetcher.scala
- src/main/scala/sangria/execution/deferred/FetcherBasedDeferredResolver.scala
- src/test/scala/sangria/execution/deferred/FetcherSpec.scala
where relation information is not contained withing domain object (usual case for many-to-many relations)
> Added ability to represent complex relations

- build.sbt
- src/main/scala/sangria/ast/QueryAst.scala
Update to match pull request against macro-visit project
> rename TransformSpecial to VisitAnyField

- src/main/scala/sangria/execution/Executor.scala
- src/main/scala/sangria/execution/Resolver.scala
- src/main/scala/sangria/execution/ValueCoercionHelper.scala
- src/main/scala/sangria/execution/ValueCollector.scala
- src/main/scala/sangria/execution/middleware.scala
- src/main/scala/sangria/schema/Context.scala
- src/main/scala/sangria/schema/SchemaValidationRule.scala
- src/main/scala/sangria/validation/Violation.scala
- src/test/scala/sangria/execution/QueryReducerSpec.scala
- src/test/scala/sangria/execution/ScalarMiddlewareSpec.scala
- src/test/scala/sangria/execution/ValueCoercionHelperSpec.scala
- src/test/scala/sangria/execution/VariablesSpec.scala
- src/test/scala/sangria/schema/EnumTypeSpec.scala
See #248 for more details. This PR implements the middleware-based approach.
Fixes #248
> Scalar-based Middleware

- src/main/scala/sangria/validation/Violation.scala
Not much to say really, stumbled upon this while reading the source :)
Thanks for the nice library! 👍
> Fixed typo in BigDecimalCoercionViolation

- src/main/scala/sangria/validation/rules/OverlappingFieldsCanBeMerged.scala
- src/test/scala/sangria/execution/ExecutorSpec.scala
- src/test/scala/sangria/validation/rules/OverlappingFieldsCanBeMergedSpec.scala
Fixes #238
Ref: https://github.com/graphql/graphql-js/pull/780
> Fixes infinite loop on invalid queries in OverlappingFields.

- src/main/scala/sangria/execution/deferred/Fetcher.scala
- src/test/scala/sangria/execution/deferred/FetcherSpec.scala
Added `relOnly` and `relOnlyCaching` methods to Fetcher object, so that the `fetch` function argument won't be a must and the `fetchRel` function argument alone can be used for creating relation based fetchers.
> Add relOnly and relOnlyCaching methods to Fetcher

- src/test/scala/sangria/marshalling/EnumInputTypeSpec.scala
> Add test case for inconsistent enum type coercion

- src/main/scala/sangria/ast/QueryAst.scala
- src/main/scala/sangria/macros/AstLiftable.scala
- src/main/scala/sangria/parser/QueryParser.scala
- src/main/scala/sangria/renderer/QueryRenderer.scala
- src/main/scala/sangria/renderer/SchemaRenderer.scala
- src/main/scala/sangria/schema/AstSchemaBuilder.scala
- src/main/scala/sangria/schema/ResolverBasedAstSchemaBuilder.scala
- src/main/scala/sangria/validation/QueryValidator.scala
- src/main/scala/sangria/validation/Violation.scala
- src/main/scala/sangria/validation/rules/ExecutableDefinitions.scala
- src/test/resources/queries/schema-kitchen-sink-pretty.graphql
- src/test/resources/scenarios/execution/Executor.yaml
- src/test/resources/scenarios/parsing/SchemaParser.yaml
- src/test/scala/sangria/execution/ExecutorSpec.scala
- src/test/scala/sangria/macros/LiteralMacroSpec.scala
- src/test/scala/sangria/parser/QueryParserSpec.scala
- src/test/scala/sangria/parser/SchemaParserSpec.scala
- src/test/scala/sangria/renderer/QueryRendererSpec.scala
- src/test/scala/sangria/renderer/SchemaRenderSpec.scala
- src/test/scala/sangria/schema/AstSchemaMaterializerSpec.scala
- src/test/scala/sangria/schema/SchemaComparatorSpec.scala
- src/test/scala/sangria/util/FileUtil.scala
- src/test/scala/sangria/validation/rules/ExecutableDefinitionsSpec.scala
> SDL Updates

- src/main/scala/sangria/execution/deferred/FetcherBasedDeferredResolver.scala
> Replaced Exception with Throwable to match all possible results of Future.failed

- src/main/scala/sangria/ast/QueryAst.scala
- src/main/scala/sangria/macros/AstLiftable.scala
- src/main/scala/sangria/parser/QueryParser.scala
- src/main/scala/sangria/renderer/QueryRenderer.scala
- src/main/scala/sangria/schema/AstSchemaBuilder.scala
- src/main/scala/sangria/schema/AstSchemaMaterializer.scala
- src/main/scala/sangria/schema/AstSchemaResolver.scala
- src/main/scala/sangria/schema/ResolverBasedAstSchemaBuilder.scala
- src/main/scala/sangria/schema/SchemaComparator.scala
- src/main/scala/sangria/validation/rules/ExecutableDefinitions.scala
- src/main/scala/sangria/validation/rules/KnownTypeNames.scala
- src/test/resources/scenarios/parsing/SchemaParser.yaml
- src/test/resources/scenarios/validation/validation.schema.graphql
- src/test/scala/sangria/execution/InputDocumentMaterializerSpec.scala
- src/test/scala/sangria/macros/LiteralMacroSpec.scala
- src/test/scala/sangria/marshalling/EnumInputTypeSpec.scala
- src/test/scala/sangria/parser/SchemaParserSpec.scala
- src/test/scala/sangria/renderer/QueryRendererSpec.scala
- src/test/scala/sangria/renderer/SchemaRenderSpec.scala
- src/test/scala/sangria/schema/AstSchemaMaterializerSpec.scala
- src/test/scala/sangria/schema/ResolverBasedAstSchemaBuilderSpec.scala
- src/test/scala/sangria/schema/SchemaComparatorSpec.scala
- src/test/scala/sangria/schema/SchemaExtensionSpec.scala
- src/test/scala/sangria/util/CatsSupport.scala
> Recent SDL syntax updates (interfaces + filed/value/type lists + new type extentions)

- .github/workflows/ci.yml
- build.sbt
follow up of https://github.com/sangria-graphql/sangria/pull/613
> publish releases

- modules/core/src/main/scala/sangria/macros/derive/GraphQLOutputTypeLookup.scala
- modules/core/src/test/scala/sangria/macros/derive/DeriveObjectTypeMacroSpec.scala
This reverts commit b4e9af334d63405d16f126f7e669c018f66da034, reversing changes made to 1d8eab6781652c695635a2b3c832f7a0f1a04a95.
Reverts https://github.com/sangria-graphql/sangria/pull/600
Fixes https://github.com/sangria-graphql/sangria/issues/615
> Revert "Merge pull request #600 from ocordsen/master"

- modules/core/src/main/scala/sangria/execution/Resolver.scala
- modules/core/src/main/scala/sangria/schema/Schema.scala
- modules/core/src/test/scala/sangria/execution/ExecutorSpec.scala
I fixed URI which provides homepage for Sangria from original one into github.io . Domain is already obsoleted.
Thanks.
> Fixed obsoleted homepage URI

- README.md
> bump the Scala versions in the project badges

- build.sbt
- modules/core/src/main/scala/sangria/ast/OperationType.scala
- modules/core/src/main/scala/sangria/ast/QueryAst.scala
- modules/core/src/main/scala/sangria/ast/package.scala
- modules/core/src/main/scala/sangria/execution/Resolver.scala
- modules/core/src/main/scala/sangria/schema/AstSchemaBuilder.scala
- modules/core/src/main/scala/sangria/schema/AstSchemaMaterializer.scala
- modules/core/src/main/scala/sangria/schema/Context.scala
- modules/core/src/main/scala/sangria/schema/Schema.scala
- modules/core/src/main/scala/sangria/schema/package.scala
Documentation and clean-up of IDE warnings related to my investigation into separating the AST package into its own module.
> document and clean the AST code

- modules/core/src/main/scala/sangria/parser/ParserConfig.scala
> make `ParserConfig.parboiledToSourceMapper` public

- modules/core/src/main/scala/sangria/execution/InputDocumentMaterializer.scala
- modules/core/src/main/scala/sangria/introspection/IntrospectionParser.scala
- modules/core/src/main/scala/sangria/package.scala
- modules/core/src/main/scala/sangria/parser/DeliveryScheme.scala
- modules/core/src/main/scala/sangria/parser/QueryParser.scala
> deprecate `DeliveryScheme`

- modules/core/src/main/scala/sangria/schema/SchemaComparator.scala
- modules/core/src/test/scala/sangria/schema/SchemaComparatorSpec.scala
http://spec.graphql.org/draft/#sec-Input-Object-Required-Fields
> mandatory fields with default values are considered optional

- build.sbt
- modules/ast/src/main/scala/sangria/ast/QueryAst.scala
- modules/core/src/main/scala/sangria/schema/Schema.scala
- modules/core/src/test/scala/sangria/schema/CustomDirectiveSpec.scala
Context: https://github.com/sangria-graphql/sangria/discussions/913
> simple API to add custom directives

- modules/core/src/main/scala/sangria/schema/Context.scala
- modules/core/src/test/scala/sangria/schema/ArgsSpec.scala
- modules/core/src/test/scala/sangria/schema/ContextArgSpec.scala
Fix https://github.com/sangria-graphql/sangria/issues/434
> fix argOpt on optional argument 

- modules/core/src/main/scala/sangria/schema/Context.scala
I got tripped up by the semantics of these, so thought I would contribute back some docs
> Add scaladoc for Arg methods

- modules/core/src/main/scala/sangria/execution/FutureResolver.scala
use tail-recursion when possible
> optimize projection

- modules/derivation/src/main/scala-2/sangria/macros/derive/DeriveEnumTypeMacro.scala
- modules/derivation/src/test/scala/sangria/macros/derive/DeriveEnumTypeMacroSpec.scala
Fix enum derivation when the enum composed of case objects but they are not within another class
> Fix enum derivation

- modules/core/src/main/scala/sangria/execution/FutureResolver.scala
> avoid seq instantiations
