build.sbt, src/main/scala/sangria/macros/AstLiftable.scala, src/main/scala/sangria/macros/literal.scala, src/test/scala/sangria/macros/LiteralMacroSpec.scala
This addresses issue #33 by adding a LiteralGraphQLStringContext  that adds a graphql method. This allows you to use string interpolation to parse a string literal into a sangria.ast.Document. This is done via a simple macro that calls QueryParse.parse on the string literal pulled from the StringContext call.
The majority of the code is in implementing the Liftable type class for all the ASTNodes. This requires quite a bit of boilerplate, but should be fine for now. Perhaps there is something available that implements this type class automatically for case classes?
This macro allows us to parse the string literal at compile time. Compilation will fail if the string cannot be parsed.
=> #33 - Macro for parsing graphql documents at compile time

.travis.yml, src/test/scala/sangria/renderer/QueryRendererSpec.scala
I didn't try out `before_cache` but have been using a similar setup to enable Travis' caching in a different project to speed up builds. Split the indentation change in a separate commit in case that matters I can either revert or squash.
Also adds a small improvement to remove some boilerplate from `QueryRendererSpec`.
=> Travis containers and caching

src/main/scala/sangria/execution/Executor.scala, src/main/scala/sangria/execution/Resolver.scala, src/test/scala/sangria/execution/DeprecationTrackerSpec.scala, src/test/scala/sangria/execution/DirectivesSpec.scala, src/test/scala/sangria/execution/ExceptionHandlingSpec.scala, src/test/scala/sangria/execution/ExecutorSchemaSpec.scala, src/test/scala/sangria/execution/ExecutorSpec.scala, src/test/scala/sangria/execution/MiddlewareSpec.scala, src/test/scala/sangria/execution/ProjectorSpec.scala, src/test/scala/sangria/execution/VariablesSpec.scala, src/test/scala/sangria/introspection/IntrospectionSpec.scala, src/test/scala/sangria/marshalling/QueryAstMarshallingSupportSpec.scala, src/test/scala/sangria/renderer/SchemaRenderSpec.scala, src/test/scala/sangria/starWars/StarWarsIntrospectionSpec.scala, src/test/scala/sangria/starWars/StarWarsQuerySpec.scala, src/test/scala/sangria/util/GraphQlSupport.scala
This change adds a `prepare` step to an execution making it much easier to make several consequent query execution. `PreparedQuery` also contains useful information abbot top-level field of the query with all of the arguments. This can be useful, for instance, for subscription queries that handled outside of the execution.
As a side-effect, some of the arguments are moved from the `Executor` to the `execute` and `prepare` methods.
=> `Prepared Query`

src/main/scala/sangria/ast/QueryAst.scala, src/main/scala/sangria/execution/Resolver.scala, src/main/scala/sangria/schema/Context.scala, src/test/scala/sangria/execution/DeferredResolverSpec.scala, src/test/scala/sangria/execution/ListsSpec.scala, src/test/scala/sangria/starWars/StarWarsQuerySpec.scala, src/test/scala/sangria/util/DebugUtil.scala, src/test/scala/sangria/util/FutureResultSupport.scala
This improves batching of deferred values on different levels of resolution. `DeferredResolver` now also provides ability to group deferred values and exclude differed value from being batch if it takes too long to retrieve it.
=> Improved deferred resolution

src/main/scala/sangria/execution/Executor.scala, src/main/scala/sangria/execution/Resolver.scala, src/main/scala/sangria/execution/ValueCollector.scala, src/main/scala/sangria/execution/deferred/DeferredResolver.scala, src/main/scala/sangria/execution/deferred/Fetcher.scala, src/main/scala/sangria/execution/deferred/FetcherBasedDeferredResolver.scala, src/main/scala/sangria/execution/deferred/FetcherCache.scala, src/main/scala/sangria/execution/deferred/HasId.scala, src/test/scala/sangria/execution/ActionMapSpec.scala, src/test/scala/sangria/execution/ExecutorSchemaSpec.scala, src/test/scala/sangria/execution/ExecutorSpec.scala, src/test/scala/sangria/execution/MiddlewareSpec.scala, src/test/scala/sangria/execution/MutationSpec.scala, src/test/scala/sangria/execution/ProjectorSpec.scala, src/test/scala/sangria/execution/VariablesSpec.scala, src/test/scala/sangria/execution/deferred/DeferredResolverSpec.scala, src/test/scala/sangria/execution/deferred/FetcherSpec.scala, src/test/scala/sangria/marshalling/QueryAstMarshallingSupportSpec.scala, src/test/scala/sangria/schema/AstSchemaMaterializerSpec.scala, src/test/scala/sangria/starWars/TestData.scala, src/test/scala/sangria/starWars/TestSchema.scala, src/test/scala/sangria/util/FutureResultSupport.scala, src/test/scala/sangria/util/GraphQlSupport.scala
It provides following features:
* It supports multiple `Fetcher`s for different entities
* Deduplicates the list of IDs
* Supports `maxBatchSize`
* Provides caching support (independent cache is used for every query execution, but it can be configured)
* has a fallback to some existing `DeferredResolver`
=> Simple high-level deferred resolution API on top of `DeferredResolver`.

src/test/scala/sangria/schema/CoercionSpec.scala
Check coercion of Double.{NaN,PositiveInfinity,NegativeInfinity} as well
as empty string.
=> Add coercion checks for more boundary values

src/main/scala/sangria/execution/ExecutionError.scala, src/main/scala/sangria/execution/Executor.scala, src/test/scala/sangria/execution/ExecutorSpec.scala
Based on #186 .
This is my first PR, so I have a bunch of questions:
Happy to fix anything, no matter how minor -- thanks for taking a look! :)
=> 186: add custom subclass for unknown operation name

src/main/scala/sangria/macros/derive/DeriveObjectSetting.scala, src/main/scala/sangria/macros/derive/DeriveObjectTypeMacro.scala, src/test/scala/sangria/macros/derive/DeriveObjectTypeMacroSpec.scala
There is an `UppercaseValues` setting for `deriveEnumType`, but no means to transform field names in `deriveObjectType`. This PR is my attempt to provide such methods. I don't really know how this issue should really be approached and this is my first take on macros :)
=> Field name transformer for `deriveObjectType`

src/main/scala/sangria/execution/Executor.scala, src/main/scala/sangria/execution/Resolver.scala, src/main/scala/sangria/execution/ValueCoercionHelper.scala, src/main/scala/sangria/introspection/package.scala, src/main/scala/sangria/renderer/SchemaRenderer.scala, src/main/scala/sangria/schema/AstSchemaMaterializer.scala, src/main/scala/sangria/schema/Context.scala, src/main/scala/sangria/schema/Schema.scala, src/main/scala/sangria/schema/SchemaComparator.scala, src/main/scala/sangria/validation/QueryValidator.scala, src/test/scala/sangria/execution/ScalarAliasSpec.scala
`ScalarAlias` represents some other scalar value (like `string`, `int`, etc.), but has its own scala type. This makes it possible to represent some custom scala class as a standard scalar GraphQL type. This also makes it easy to transparently add validations for standard scalars.
Here is an example of how it will look like in code:
```scala
implicit val UserIdType = ScalarAlias[UserId, String](StringType, _.id, id ⇒ Right(UserId(id)))
```
Closes #210
=> Scalar Alias

src/main/scala/sangria/schema/AstSchemaBuilder.scala, src/main/scala/sangria/schema/Context.scala, src/main/scala/sangria/schema/IntrospectionSchemaBuilder.scala, src/main/scala/sangria/schema/Schema.scala, src/main/scala/sangria/schema/SchemaComparator.scala, src/test/scala/sangria/schema/SchemaComparatorSpec.scala
This also adds `Vector[ast.Directive]` to all relevant schema definitions which may be extremely useful for future features and schema analysis
=> Preserve IDL directives at schema materialization time and use them in schema comparator

src/main/scala/sangria/execution/Resolver.scala, src/main/scala/sangria/execution/ValueCoercionHelper.scala, src/main/scala/sangria/execution/ValueCollector.scala, src/main/scala/sangria/schema/AstSchemaBuilder.scala, src/main/scala/sangria/schema/AstSchemaMaterializer.scala, src/test/scala/sangria/execution/MiddlewareSpec.scala, src/test/scala/sangria/execution/ScalarAliasSpec.scala
When schema is extended, scala aliases were partially erased from the schema. Verifiable resolution logic have not considered scala aliases either.
=> Fixed scalar aliases when they are used with variables or schema is extended

src/main/scala/sangria/schema/Context.scala, src/test/scala/sangria/schema/ArgsSpec.scala
I'd like a helper be able to generate `Args` based on argument definitions and provided inputs. Generating Args manually can be rather tedious and a lot of the work seems like it can be abstracted away.
=> Create args builder

src/main/scala/sangria/execution/QueryReducer.scala, src/test/scala/sangria/execution/QueryReducerSpec.scala
=> Fix `MeasureQueryDepth` reducer not keeping the largest depth found

src/main/scala/sangria/schema/package.scala, src/test/scala/sangria/introspection/IntrospectionSpec.scala, src/test/scala/sangria/renderer/SchemaRenderSpec.scala
For reference, the space is not missing in the JS version: https://github.com/graphql/graphql-js/blob/831598ba76f015078ecb6c5c1fbaf133302f3f8e/src/type/directives.js#L169-L171
=> Add missing space in the description of the deprecation reason argument

src/main/scala/sangria/schema/Schema.scala, src/test/scala/sangria/introspection/IntrospectionSpec.scala, src/test/scala/sangria/schema/SchemaComparatorSpec.scala, src/test/scala/sangria/starWars/StarWarsIntrospectionSpec.scala
=> Built in scalars will now only be added to the schema if they are used

src/main/scala/sangria/renderer/QueryRenderer.scala, src/test/scala/sangria/renderer/QueryRendererSpec.scala
Currently if a directive doesn't have any arguments which is possible [per spec](https://facebook.github.io/graphql/#sec-Language.Directives) both compact and pretty printing doesn't have a space between the directive name and `on ...`
So it renders it like so for a directive named "custom"
```graphql
directive @customon FIELD
```
This PR fixes the behaviour so it renders
```graphql
directive @custom on FIELD
```
I didn't updated the kitchen sink test as it's breaking the expectations of the query parser test and I'll be honest I have no idea how to update that one
=> Fixed directive definition rendering in query renderer

src/main/scala/sangria/macros/derive/DeriveEnumTypeMacro.scala
This typo was vicious as it changed the original intended meaning. (just lost an hour because of it :smile: )
=> Fix typo in error message.

.travis.yml, build.sbt, src/main/scala/sangria/ast/QueryAst.scala, src/main/scala/sangria/execution/ExecutionError.scala, src/main/scala/sangria/execution/InputDocumentMaterializer.scala, src/main/scala/sangria/execution/ValueCoercionHelper.scala, src/main/scala/sangria/macros/AstLiftable.scala, src/main/scala/sangria/macros/ParseMacro.scala, src/main/scala/sangria/macros/package.scala, src/main/scala/sangria/parser/QueryParser.scala, src/main/scala/sangria/renderer/QueryRenderer.scala, src/main/scala/sangria/renderer/SchemaRenderer.scala, src/main/scala/sangria/schema/Schema.scala, src/main/scala/sangria/validation/QueryValidator.scala, src/main/scala/sangria/validation/TypeInfo.scala, src/main/scala/sangria/validation/Violation.scala, src/main/scala/sangria/validation/rules/InputDocumentNonConflictingVariableInference.scala, src/main/scala/sangria/validation/rules/InputDocumentOfCorrectType.scala, src/test/resources/scenarios/validation/DefaultValuesOfCorrectType.yaml, src/test/scala/sangria/execution/InputDocumentMaterializerSpec.scala, src/test/scala/sangria/execution/ScalarAliasSpec.scala, src/test/scala/sangria/execution/VariablesSpec.scala, src/test/scala/sangria/util/DebugUtil.scala, src/test/scala/sangria/util/ValidationSupport.scala, src/test/scala/sangria/validation/rules/ArgumentsOfCorrectTypeSpec.scala, src/test/scala/sangria/validation/rules/DefaultValuesOfCorrectTypeSpec.scala, src/test/scala/sangria/validation/rules/InputDocumentNonConflictingVariableInferenceSpec.scala, src/test/scala/sangria/validation/rules/InputDocumentOfCorrectTypeSpec.scala
This PR improves on ideas described in this post:
https://medium.com/@oleg.ilyenko/graphql-object-notation-8f56194556ea
It adds an easier way to validate and materialize/deserialize input document. You can find some example of usage in this test: https://github.com/sangria-graphql/sangria/pull/272/files#diff-b6eed12a7a0cf608e15570a6fc3f868fR57
=> Improved input document validation and deserialization

src/main/scala/sangria/ast/QueryAst.scala, src/main/scala/sangria/execution/SimpleExtensionMiddleware.scala, src/main/scala/sangria/execution/batch/BatchExecutionPlan.scala, src/main/scala/sangria/execution/batch/BatchExecutor.scala, src/main/scala/sangria/execution/batch/batchViolations.scala, src/main/scala/sangria/execution/middleware.scala, src/main/scala/sangria/marshalling/ImprovedMarshallingUtil.scala, src/main/scala/sangria/marshalling/SymmetricMarshaller.scala, src/main/scala/sangria/renderer/SchemaRenderer.scala, src/test/scala/sangria/execution/batch/BatchExecutorSpec.scala, src/test/scala/sangria/util/GraphQlSupport.scala
This batch executor implementation is inspired by this talk:
[![batch](https://user-images.githubusercontent.com/156569/28756687-928d7598-7573-11e7-8902-77745768b5e7.png)](https://youtu.be/ViXL0YQnioU?t=10m26s)
It provides following features:
* Allows specifying multiple `operationNames` when executing a GraphQL query document. All operations would be executed in order inferred from the dependencies between queries.
* Support for `@export(as: "foo")` directive. This directive allows you to save the results of the query execution and then use it as a variable in a different query within the same document. This provides a way to define data dependencies between queries.
* When used with `@export` directive, the variables would be automatically inferred by the execution engine, so you don't …
=> Batch Executor

src/main/scala/sangria/execution/DeprecationTracker.scala, src/main/scala/sangria/execution/Executor.scala, src/main/scala/sangria/execution/InputDocumentMaterializer.scala, src/main/scala/sangria/execution/QueryReducer.scala, src/main/scala/sangria/execution/QueryReducerExecutor.scala, src/main/scala/sangria/execution/TimeMeasurement.scala, src/main/scala/sangria/execution/ValueCollector.scala, src/main/scala/sangria/schema/package.scala, src/test/scala/sangria/execution/DeprecationTrackerSpec.scala, src/test/scala/sangria/execution/QueryReducerSpec.scala, src/test/scala/sangria/execution/ValueCoercionHelperSpec.scala
This is a quick-and-dirty sketch for what #277 might look like. 
The basic approach is to add a new `Executor.prepare` method that doesn't accept variables, and add `preparedQueryReducers` to `Executor`.
Query reducers are run depending on the scenario:
* If we are preparing a query *without* known variables
+ Run `preparedQueryReducers` now and defer `queryReducers` to runtime
* If we are preparing a query *with* known variables
+ Run `preparedQueryReducers` and `queryReducers` now
* If we are executing an unprepared query:
+ Run `queryReducers`
The implementation is complete enough for my use case, but is not merge-ready.
What do you think about separating preparation-time from run-time like this?
=> Prepared queries without variables

src/main/scala/sangria/execution/Executor.scala, src/main/scala/sangria/execution/QueryReducerExecutor.scala, src/test/scala/sangria/execution/ExecutorSpec.scala
In #281 , unmarshalled variables stopped being passed from the executor to the query reducer executor. This means that variables and query reducers no longer work together--the unit tests show that they work independently, but there was no integration test for the two components.
This fixes it, and adds a regression test.
=> Fix regression where variables aren't passed to query reducers

src/main/scala/sangria/ast/QueryAst.scala, src/main/scala/sangria/execution/Resolver.scala, src/main/scala/sangria/execution/batch/BatchExecutor.scala, src/main/scala/sangria/macros/AstLiftable.scala, src/main/scala/sangria/marshalling/queryAst.scala, src/main/scala/sangria/parser/QueryParser.scala, src/main/scala/sangria/renderer/QueryRenderer.scala, src/main/scala/sangria/schema/AstSchemaBuilder.scala, src/main/scala/sangria/schema/package.scala, src/main/scala/sangria/util/StringUtil.scala, src/test/resources/queries/block-string-rendered.graphql, src/test/resources/queries/block-string.graphql, src/test/scala/sangria/execution/QueryReducerSpec.scala, src/test/scala/sangria/macros/LiteralMacroSpec.scala, src/test/scala/sangria/marshalling/IonSupportSpec.scala, src/test/scala/sangria/parser/QueryParserSpec.scala, src/test/scala/sangria/parser/SchemaParserSpec.scala, src/test/scala/sangria/renderer/QueryRendererSpec.scala, src/test/scala/sangria/schema/CustomScalarSpec.scala, src/test/scala/sangria/schema/ResolverBasedAstSchemaBuilderSpec.scala, src/test/scala/sangria/schema/SchemaConstraintsSpec.scala, src/test/scala/sangria/schema/SchemaDefinitionSpec.scala, src/test/scala/sangria/util/CatsSupport.scala, src/test/scala/sangria/util/StringUtilSpec.scala
Adds support for block strings ([spec change](https://github.com/facebook/graphql/pull/327)):
```graphql
mutation {
sendEmail(message: """
Hello,
World!
Yours,
GraphQL.
""")
}
```
Closes #260
=> Block String Support

src/main/scala/sangria/macros/derive/GraphQLOutputTypeLookup.scala
For context from the gitter channel.
> Hey all, I seem to be having a problem with the `deriveContextObjectType` when one of the derived type's methods returns an `interface` type. I receive a `Can't find suitable GraphQL output type for services.tag.GenericTag. If you have defined it already, please consider making it implicit and ensure that it's available in the scope.` Error during compilation instead. Is this a known limitation? It seems to work if I switch the return type to a concrete type...
e.g.
```scala
// In Mutation.scala
trait Mutation {
@GraphQLField
addTag: Future[GenericTag] = {} // GenericTag has a GraphQL InterfaceType declaration
}
// in SchemaDefinition.scala
implicit val TagType = InterfaceType("Tag", "",  () => fields[UserContext, GenericTag]()
implicit val …
```
=> Support implicit output lookups for interface types

src/main/scala/sangria/macros/derive/GraphQLOutputTypeLookup.scala
Reverts sangria-graphql/sangria#306
=> Revert "Support implicit output lookups for interface types"

src/main/scala/sangria/macros/derive/DeriveObjectTypeMacro.scala
The Scala compiler uses laziness extensively to deal with recursive types. Annotations are one instance where an uninitialized type will be incorrect, so we call `info` before checking method annotations inside macros. The proper method, initialize, is not available in the public API so I just called .info, which is what most places in the compiler do, anyway.
Fix #172
=> Initialize symbols before checking their annotations.

src/main/scala/sangria/validation/TypeInfo.scala, src/main/scala/sangria/validation/rules/PossibleFragmentSpreads.scala
Add document field to TypeInfo so it can resolve fragment definitions
and provide type information for fragment spreads.
---
Motivated by [this case in sangria-codegen](https://github.com/mediative/sangria-codegen/blob/1f36a8458329bbbb2e1b31099811316cbf48d052/sangria-codegen/src/main/scala/com.mediative.sangria.codegen/Importer.scala#L99-L105). This complicates downstreams users of `TypeInfo` by requiring the document AST instance up front. Another way to go would be for `TypeInfo` to keep a "document AST stack" and optionally resolve fragment spreads if a previous `TypeInfo.enter(ast.Document)` call was made.
=> RFC: Resolve type info for fragment spreads

build.sbt, src/main/scala/sangria/macros/derive/DeriveObjectSetting.scala, src/main/scala/sangria/macros/derive/DeriveObjectTypeMacro.scala, src/test/scala/sangria/macros/derive/DeriveObjectTypeMacroSpec.scala
#318: Added the following `DeriveObjectSetting`s:
| Setting name | Description |
|------------------|----------------|
| `MethodArgumentRename` | change name of single argument |
| `MethodArgumentDescription` | set description for a single argument |
| `MethodArgumentsDescription` | set descriptions for multiple arguments |
| `MethodArgumentDefault` | set default value for a single argument |
| `MethodArgument` | set description and default value for a single argument |
=> Allow to rename, describe and set default arguments using `DeriveObjectSetting`s.

src/main/scala/sangria/schema/Schema.scala, src/main/scala/sangria/validation/Violation.scala, src/test/scala/sangria/schema/SchemaConstraintsSpec.scala, src/test/scala/sangria/schema/bar/Baz.scala, src/test/scala/sangria/schema/foo/Baz.scala
If two or more case classes with the same name in different packages are used to derive `ObjectType`s Sangria will silently choose one of them and ignore the others. This PR makes it so that an exception is thrown if two `ObjectType`s are found with the same name but derived from different case classes.
=> Don't allow ObjectTypes derived from case classes to overwrite each other

src/main/scala/sangria/execution/middleware.scala
Did a code search and found no use for this field. So this should be a safe fix.
=> Fix BeforeFieldResult field name

src/main/scala/sangria/macros/derive/DeriveEnumSetting.scala, src/main/scala/sangria/macros/derive/DeriveEnumTypeMacro.scala, src/test/scala/sangria/macros/derive/DeriveEnumTypeMacroSpec.scala
Added a derivation setting for transforming GraphQL enum values, similar to `TransformFieldNames`.
Since graphql has no definition scopes, the following scala enums will cause collision:
```scala
sealed trait Color
object Color {
case object Red extends Color
case object Blue extends Color
case object Green extends Color
// etc
}
sealed trait TrafficLight
object TrafficLight {
case object Red extends TrafficLight
case object Yellow extends TrafficLight
case object Green extends TrafficLight
}
```
The solution might be adding a prefix to graphql enum values, renaming, for example, traffic light colors to `TrafficLightRed`, `TrafficLightYellow` and `TrafficLightGreen`.
------------------------
The proposed setting should allow to do it in bulk.
=> Transform enum values' names with a macro setting

src/main/scala/sangria/execution/Resolver.scala, src/main/scala/sangria/schema/Schema.scala, src/test/scala/sangria/execution/UnionInterfaceSpec.scala
- Since Scala 2.x does not have union types, one can represent them a
number of different ways, a common way is to use a boxed type like Either,
or Coproduct from various libraries.  To use these boxed types is impossible
in Sangria because it basically expects the type to unboxed, and
inheriting from `Any` is the only way to achieve that.
- This introduces a concept to map a type `T` to Any such that you can unbox
after the definition, and get a value what the native type defs expect.
=> Add a `MappedAbstractType` that will transform the input value

build.sbt
instead of using the JVM version of the locally used JVM, control the target version
=> emit jvm 8 bytecode for scala >= 2.12

README.md
The links are still to the old dead website.
Unfortunately we don't have "Try Sangria" running anywhere, so the link is updated to point at
the playground repo so people can run it themselves.
=> Fix broken website links in README

modules/core/src/main/scala/sangria/validation/rules/KnownTypeNames.scala, modules/core/src/test/scala/sangria/validation/rules/KnownTypeNamesDisabledSpec.scala
By overriding the default QueryValidator, one can disable or add a cache for the suggested fields.
Fixes https://github.com/sangria-graphql/sangria/issues/497
=> can disable expensive suggestions

modules/benchmarks/README.md, modules/benchmarks/src/main/scala/sangria/benchmarks/StringUtilBenchmark.scala, modules/core/src/main/scala/sangria/util/StringUtil.scala, modules/core/src/test/scala/sangria/util/StringUtilSpec.scala
benchmark results are in the first commit
=> Faster suggestion list

modules/core/src/main/scala/sangria/macros/derive/DeriveInputObjectTypeMacro.scala, modules/core/src/main/scala/sangria/macros/derive/DeriveObjectTypeMacro.scala, modules/core/src/test/scala/sangria/macros/derive/DeriveInputObjectTypeMacroSpec.scala, modules/core/src/test/scala/sangria/macros/derive/DeriveMacroTestModel.scala, modules/core/src/test/scala/sangria/macros/derive/DeriveObjectTypeMacroSpec.scala
For macro-based schema derivation
Resolves #261
This is #457 but rebased :)
=> Correctly resolve member types of type-parameterized classes

.gitignore, .travis.yml, build.sbt
2.11 targets JVM 7 which is old and stinky, this moves us into the future of Long Term support!
=> Remove Scala 2.11 Support 🔥

modules/core/src/main/scala/sangria/schema/AstSchemaBuilder.scala, modules/core/src/main/scala/sangria/schema/Schema.scala, modules/core/src/test/scala/sangria/schema/IntrospectionSchemaMaterializerSpec.scala
Moves `types` for `UnionType` to be defined as a no-arg method à la `fieldsFn` on `Field`.
=> Lazy Union Types

modules/core/src/main/scala/sangria/execution/deferred/Fetcher.scala, modules/core/src/main/scala/sangria/execution/deferred/FetcherBasedDeferredResolver.scala, modules/core/src/main/scala/sangria/introspection/IntrospectionParser.scala, modules/core/src/main/scala/sangria/validation/DocumentAnalyzer.scala
I'm trying to understand the code a little better and applying small refactorings here and there.
I'm grouping them by theme, so that changes you don't like can be taken out.
Any comments welcome :smiley:
=> Assorted refactorings

modules/core/src/main/scala/sangria/validation/TypeInfo.scala, modules/core/src/main/scala/sangria/validation/rules/OverlappingFieldsCanBeMerged.scala
This is a continuation of #404, with items that Oleg had indicated as potentially risky due to performance implications as mentioned here: https://github.com/sangria-graphql/sangria/pull/404#pullrequestreview-162264728
I'd like to keep the changes around, so I have split this into a separate PR in hopes that we can come up with a plan to validate, or disprove Oleg's concerns.
=> Assorted Refactorings Part 2

build.sbt, modules/core/src/main/scala/sangria/execution/Resolver.scala, modules/core/src/main/scala/sangria/schema/Context.scala, modules/core/src/test/scala/sangria/execution/ProjectorSpec.scala
After a little digging, thanks to @kirach's fork, I saw that the fix for the problem @yanns ran into https://github.com/sangria-graphql-org/sangria/pull/10#issuecomment-571471876 was a trivial fix.
I also updated the test cases to ensure queries with variables are a tested case.
Closing #468 in favor of this due to nasty rebasing from a long out of date branch :)
=> Support Args in ProjectedNames

modules/core/src/main/scala/sangria/macros/derive/GraphQLOutputTypeLookup.scala, modules/core/src/test/scala/sangria/macros/derive/DeriveObjectTypeMacroSpec.scala
This is a new version of https://github.com/sangria-graphql/sangria/pull/306. I hope it maybe can be merged or perhaps it leads to another idea to solve the problem with Interface-Types that cannot be found. All context is in the original pull request so I keep it short here. :)
=> Support implicit output type lookups for interface types.

modules/core/src/main/scala/sangria/schema/Schema.scala, modules/core/src/main/scala/sangria/validation/Violation.scala, modules/core/src/test/scala/sangria/schema/SchemaConstraintsSpec.scala
The validation only checks the field names. It cannot catch all cases, but I think it should be sufficient for 99% of the cases.
=> validate that different instances of InputObjectType with the same name are the same

.scalafmt.conf, build.sbt, modules/core/src/main/scala/sangria/execution/deferred/Fetcher.scala, modules/core/src/main/scala/sangria/execution/deferred/FetcherBasedDeferredResolver.scala, modules/core/src/main/scala/sangria/schema/Context.scala
added a new config param maxConcurrentBatches to configure
the max number of batched IDs that can be fetched concurrently by fetcher.
not specifying any value for this param will fallback to the existing
behaviour of running all batches concurrently.
=> support for configuring max concurrent batches in fetcher

modules/core/src/main/scala/sangria/execution/ValueCoercionHelper.scala
This function shows up while profiling mostly due to the creation of the `View` which is not strictly necessary.
The proposed implementation only relies on `collectFirst` which should be significantly faster than `view.collect.headOption`
=> Minor performance optimization to ValueCoercionHelper.valuePosition

build.sbt, modules/core/src/main/scala/sangria/ast/AstLocation.scala, modules/core/src/main/scala/sangria/ast/AstVisitorCommand.scala, modules/core/src/main/scala/sangria/ast/DefaultAstVisitor.scala, modules/core/src/main/scala/sangria/ast/OperationType.scala, modules/core/src/main/scala/sangria/ast/QueryAst.scala, modules/core/src/main/scala/sangria/ast/package.scala, modules/core/src/main/scala/sangria/marshalling/queryAst.scala, modules/core/src/main/scala/sangria/parser/ParserConfig.scala, modules/core/src/main/scala/sangria/parser/PositionTracking.scala, modules/core/src/main/scala/sangria/parser/QueryParser.scala, modules/core/src/main/scala/sangria/parser/SourceMapper.scala
Also:
- adds type annotations to public members, to address IDE warnings
- adds `override` modifiers
- moves some types from the huge QueryAst.scala file to their own files
=> document some of the AST & parser packages

modules/core/src/main/scala/sangria/execution/ExecutionPath.scala, modules/core/src/test/scala/sangria/execution/DeprecationTrackerSpec.scala
From https://github.com/sangria-graphql/sangria/pull/775
and https://github.com/sangria-graphql/sangria/pull/774
By using this in sangria-slow-logs, we will be able to generate much less objects.
=> backport ExecutionPath.cacheKeyReversed

modules/core/src/main/scala/sangria/execution/ExecutionPath.scala, modules/core/src/test/scala/sangria/execution/DeprecationTrackerSpec.scala
same API as in sangria 2.x: https://github.com/sangria-graphql/sangria/pull/781
It will allow to optimize sangria-slow-logs
=> introduce ExecutionPath.cacheKeyReversedIterator

modules/core/src/main/scala/sangria/ast/QueryAst.scala, modules/core/src/main/scala/sangria/package.scala, modules/core/src/main/scala/sangria/renderer/QueryRenderer.scala, modules/core/src/main/scala/sangria/schema/AstNodeTransformer.scala
=> deprecate & backport for AST separation

modules/core/src/main/scala/sangria/renderer/QueryRenderer.scala, modules/core/src/test/scala/sangria/renderer/SchemaRenderSpec.scala
sangria should impose any style for line breaks.
Sangria should output whatever the user has written in the documentation, letting the user control how to render line breaks.
=> Description with empty line rendering

.github/workflows/ci.yml, build.sbt
Some IDEA are not yet ready for scala 3.
Using scala 2.13 by default is a better dev experience.
=> use scala 2.13 by default

modules/core/src/main/scala/sangria/ast/AstVisitor.scala, modules/core/src/main/scala/sangria/ast/DefaultAstVisitor.scala
Use an empty PartialFunction by default, to avoid calling apply on it (shortcuts with `isDefinedAt`).
=> Optimize AstVisitor

modules/core/src/main/scala/sangria/execution/ExecutionError.scala, modules/core/src/main/scala/sangria/execution/Resolver.scala, modules/core/src/main/scala/sangria/execution/ResultResolver.scala, modules/core/src/test/scala/sangria/execution/ExceptionHandlingSpec.scala, modules/core/src/test/scala/sangria/execution/ExecutorSpec.scala, modules/core/src/test/scala/sangria/execution/QueryReducerSpec.scala, modules/core/src/test/scala/sangria/execution/VariablesSpec.scala, modules/core/src/test/scala/sangria/execution/deferred/DeferredResolverSpec.scala, modules/core/src/test/scala/sangria/execution/deferred/FetcherSpec.scala, modules/core/src/test/scala/sangria/schema/AstSchemaMaterializerSpec.scala, modules/core/src/test/scala/sangria/schema/CustomScalarSpec.scala, modules/core/src/test/scala/sangria/schema/EnumTypeSpec.scala, modules/core/src/test/scala/sangria/schema/IntrospectionSchemaMaterializerSpec.scala, modules/core/src/test/scala/sangria/schema/SchemaExtensionSpec.scala, modules/core/src/test/scala/sangria/schema/TypeFieldConstraintsSpec.scala, modules/core/src/test/scala/sangria/util/GraphQlSupport.scala
See https://spec.graphql.org/October2021/#sec-Data
If the error happened before the execution, the response should not include the `data` field.
Otherwise, the response should include a `null` `data` field.
=> different error format if before execution

modules/core/src/test/scala/sangria/schema/ArgsSpec.scala
- See https://github.com/sangria-graphql/sangria/issues/945
- Unit tests added to demonstrate the possible issue with `Args` that wraps optional arguments inside another `Option`;
=> Demonstrate Nested Optional Arguments with Unit Tests

modules/core/src/main/scala/sangria/introspection/package.scala, modules/core/src/test/resources/scenarios/execution/UnionInterface.yaml, modules/core/src/test/scala/sangria/execution/UnionInterfaceSpec.scala, modules/core/src/test/scala/sangria/introspection/InterfaceOfInterfaceSpec.scala
Follow-up of https://github.com/sangria-graphql/sangria/pull/956
Steps to reproduce:
```
{
__schema {
types {
name
interfaces {
name
}
}
}
}
```
returns:
```
...
{ "name" : "SomeInterfaceName", "interfaces" : null } 
...
```
but according to specs it should return:
```
...
{ "name" : "SomeInterfaceName", "interfaces" : [] } 
...
```
More details: https://spec.graphql.org/October2021/#sec-The-__Type-Type.Interface
> interfaces must return the set of interfaces that an object implements (if none, interfaces must return the empty set).
Knowing that [sangria does not support interfaces of interfaces for now](https://github.com/sangria-graphql/sangria/pull/597), we just change the introspection result to render an empty array instead of null.
=> 'interfaces' on interface should be an empty list

modules/core/src/main/scala/sangria/introspection/package.scala
The change https://github.com/sangria-graphql/sangria/pull/960 introduces some support for interfaces of interface.
But this feature is not complete: it would need something like https://github.com/sangria-graphql/sangria/pull/597 for full support.
Right now, sometimes we support interfaces of interface and sometimes now.
To avoid this configuration, let's always return an empty list.
We can tackle the complete support for interfaces of interface later.
=> always return an empty list for interfaces of interface

.github/workflows/ci.yml, build.sbt, modules/core/src/main/scala/sangria/execution/ExecutionScheme.scala, modules/core/src/main/scala/sangria/execution/Resolver.scala, modules/test-cats-effect/src/test/scala/sangria/execution/IOExecutionScheme.scala
The integration with [cats effect IO](https://typelevel.org/cats-effect/) is far away from being complete.
But we will go little step by little step here, exploring how far we can go without breaking backwards compatibility.
=> Very minimal integration with cats effect IO

modules/core/src/main/scala/sangria/schema/package.scala
In our project which is based on Sangria we generate pages with all types that exists in our schema. Including scalar types from Sangria. 
We have tests that verify links in types descriptions. These tests started to fail with timeout for `http://en.wikipedia.org/wiki/IEEE_floating_point`, so I checked the link of IEEE 754 wikipedia page and issued this PR with up to date link
=> Update IEEE 754 wikipedia page link

build.sbt, modules/core/src/main/scala/sangria/execution/Resolver.scala
make `sangria.execution.Resolver` private. This enables us to change the implementation without breaking backwards compatibility.
I don't think anyone is using this directly. I'll cut a RC with that to check.
If it's an issue, I'll revert this.
=> sangria.execution.Resolver is now private

build.sbt, modules/ast/src/main/scala/sangria/ast/QueryAst.scala, modules/core/src/main/scala-2/sangria/macros/AstLiftable.scala, modules/core/src/main/scala-3/sangria/macros/ToExprGivens.scala, modules/core/src/main/scala/sangria/ast/AstVisitor.scala, modules/core/src/main/scala/sangria/introspection/IntrospectionParser.scala, modules/core/src/main/scala/sangria/introspection/model.scala, modules/core/src/main/scala/sangria/introspection/package.scala, modules/core/src/main/scala/sangria/renderer/QueryRenderer.scala, modules/core/src/main/scala/sangria/renderer/SchemaRenderer.scala, modules/core/src/main/scala/sangria/schema/AstSchemaBuilder.scala, modules/core/src/main/scala/sangria/schema/AstSchemaMaterializer.scala, modules/core/src/main/scala/sangria/schema/IntrospectionSchemaBuilder.scala, modules/core/src/main/scala/sangria/schema/IntrospectionSchemaMaterializer.scala, modules/core/src/main/scala/sangria/schema/Schema.scala, modules/core/src/main/scala/sangria/schema/SchemaValidationRule.scala, modules/core/src/main/scala/sangria/validation/Violation.scala, modules/core/src/test/scala/sangria/renderer/SchemaRenderSpec.scala, modules/core/src/test/scala/sangria/schema/AstSchemaMaterializerSpec.scala, modules/derivation/src/test/scala/sangria/schema/SchemaConstraintsSpec.scala, modules/parser/src/main/scala/sangria/parser/QueryParser.scala, modules/parser/src/test/scala/sangria/parser/SchemaParserSpec.scala
This is an initial support for #567 and supersede #597 that is based on very old base
The rendering has been a bit challenging and I took a non-standard path there
=> Add support for interface implementing interface

modules/core/src/main/scala/sangria/schema/Schema.scala, modules/core/src/main/scala/sangria/validation/TypeComparators.scala, modules/derivation/src/test/scala/sangria/schema/SchemaConstraintsSpec.scala
Fix the isSubType of typeComparator and add specific tests
=> Fix TypeComparators

.github/workflows/ci.yml, build.sbt
Scala 3.3 is a big release since its LTS, which means it will be supported for a long time (critical bugs/security fixes will be backported to the 3.3 branch) so its a good idea to prune out any potential issues before the release is made.
=> scala 3.3.0

build.sbt, modules/benchmarks/src/main/scala/sangria/benchmarks/OverlappingFieldsCanBeMergedBenchmark.scala, modules/core/src/main/scala/sangria/validation/QueryValidator.scala, modules/core/src/test/scala/sangria/util/CatsSupport.scala, modules/core/src/test/scala/sangria/util/ValidationSupport.scala, modules/core/src/test/scala/sangria/validation/QueryValidatorSpec.scala
Add an option to limit the number of errors returned.
There is a possibility that the lack of limits could be abused to induce memory pressure in the server/service handling the request and can lead to the potential denial of service (i.e. no DDoS needed).
=> Add an option to limit number of errors returned

.github/workflows/ci.yml, build.sbt, modules/benchmarks/src/main/scala/sangria/benchmarks/OverlappingFieldsCanBeMergedBenchmark.scala, modules/core/src/main/scala/sangria/execution/Executor.scala, modules/core/src/main/scala/sangria/execution/QueryReducerExecutor.scala, modules/core/src/main/scala/sangria/execution/ValueCoercionHelper.scala, modules/core/src/main/scala/sangria/execution/ValueCollector.scala, modules/core/src/main/scala/sangria/execution/batch/BatchExecutor.scala, modules/core/src/main/scala/sangria/schema/ResolverBasedAstSchemaBuilder.scala, modules/core/src/main/scala/sangria/validation/QueryValidator.scala, modules/core/src/test/scala/sangria/execution/VariablesSpec.scala, modules/core/src/test/scala/sangria/starWars/StartWarsValidationSpec.scala, modules/core/src/test/scala/sangria/util/CatsSupport.scala, modules/core/src/test/scala/sangria/util/GraphQlSupport.scala, modules/core/src/test/scala/sangria/util/ValidationSupport.scala, modules/core/src/test/scala/sangria/validation/QueryValidatorSpec.scala
Follow up to https://github.com/sangria-graphql/sangria/pull/1017
The solution from the previous PR works only for cases where input is specified (hardcoded) as a part of the query but doesn't work/executed when variables are used. For example, the following query will still return an unlimited number of errors:
```
mutation createProduct($input: CreateProductInput!) {
product {
createProduct(input: $input) {
...
}
}
}
// variables
{
"input":{
"field_with_invalid_objects":[{},{},{},{},{}, ...]
}
}
```
=> Limit number of errors returned (when variables are used)

modules/core/src/main/scala/sangria/execution/Executor.scala
Use secure configuration by default
Follow-up of https://github.com/sangria-graphql/sangria/pull/1034
=> use a max number of errors by default

build.sbt, modules/core/src/main/scala/sangria/introspection/IntrospectionParser.scala, modules/core/src/main/scala/sangria/introspection/model.scala, modules/core/src/main/scala/sangria/introspection/package.scala, modules/core/src/main/scala/sangria/renderer/SchemaRenderer.scala, modules/core/src/main/scala/sangria/schema/AstSchemaBuilder.scala, modules/core/src/main/scala/sangria/schema/IntrospectionSchemaBuilder.scala, modules/core/src/main/scala/sangria/schema/Schema.scala, modules/core/src/main/scala/sangria/schema/SchemaComparator.scala, modules/core/src/main/scala/sangria/schema/package.scala, modules/core/src/main/scala/sangria/validation/SchemaBasedDocumentAnalyzer.scala, modules/core/src/main/scala/sangria/validation/TypeInfo.scala, modules/core/src/test/scala/sangria/introspection/IntrospectionSpec.scala, modules/core/src/test/scala/sangria/renderer/SchemaRenderSpec.scala, modules/core/src/test/scala/sangria/schema/IntrospectionSchemaMaterializerSpec.scala, modules/core/src/test/scala/sangria/schema/SchemaComparatorSpec.scala, modules/core/src/test/scala/sangria/util/StringMatchers.scala, modules/core/src/test/scala/sangria/validation/DocumentAnalyzerSpec.scala, modules/derivation/src/test/scala/sangria/macros/derive/DeriveObjectTypeMacroSpec.scala
Input value deprecation is a feature added a few years ago elsewhere that we would like to add support for. See [here](https://github.com/graphql/graphql-js/blob/main/src/utilities/getIntrospectionQuery.ts#L34) and [here](https://github.com/graphql/graphql-js/blob/7a6d055defd7a888f50c6133faae2b9010d45fad/src/type/directives.ts#L220) for graphql-js usage in introspection.
There are two main things I believe I still need to work on, one of which particularly I'd like some input on.
- ~~[x] add to deprecation tracking~~ removed
~~Regarding directives, when looking at tests in `DocumentAnalyzerSpec` and `IntrospectionSchemaMaterializerSpec`, I would like to test a field having a directive with a deprecated argument. However, the field only has `ast.Directive`s on it, which lack deprecation …
=> add input value deprecation

modules/core/src/main/scala/sangria/schema/Schema.scala, modules/core/src/test/scala/sangria/introspection/IntrospectionSpec.scala
Currently we're only including unused types in the additional types of ast based schemas. This causes enums that are only used on directive args to be missed when generating an introspection query result, as we are not collecting types on directive args.
=> include enums on directive args in schema introspection

build.sbt, modules/benchmarks/src/main/scala/sangria/benchmarks/OverlappingFieldsCanBeMergedBenchmark.scala, modules/core/src/main/scala/sangria/execution/Executor.scala, modules/core/src/main/scala/sangria/execution/InputDocumentMaterializer.scala, modules/core/src/main/scala/sangria/execution/QueryReducerExecutor.scala, modules/core/src/main/scala/sangria/execution/batch/BatchExecutor.scala, modules/core/src/main/scala/sangria/schema/ResolverBasedAstSchemaBuilder.scala, modules/core/src/main/scala/sangria/schema/SchemaComparator.scala, modules/core/src/main/scala/sangria/schema/SchemaValidationRule.scala, modules/core/src/main/scala/sangria/schema/package.scala, modules/core/src/main/scala/sangria/validation/QueryValidator.scala, modules/core/src/main/scala/sangria/validation/Violation.scala, modules/core/src/main/scala/sangria/validation/rules/ExactlyOneOfFieldGiven.scala, modules/core/src/test/scala/sangria/execution/InputDocumentMaterializerSpec.scala, modules/core/src/test/scala/sangria/introspection/IntrospectionSpec.scala, modules/core/src/test/scala/sangria/schema/AstSchemaMaterializerSpec.scala, modules/core/src/test/scala/sangria/schema/SchemaComparatorSpec.scala, modules/core/src/test/scala/sangria/starWars/StartWarsValidationSpec.scala, modules/core/src/test/scala/sangria/util/CatsSupport.scala, modules/core/src/test/scala/sangria/util/ValidationSupport.scala, modules/core/src/test/scala/sangria/validation/QueryValidatorSpec.scala, modules/core/src/test/scala/sangria/validation/rules/ExactlyOneOfFieldGivenSpec.scala
Issue:
https://github.com/sangria-graphql/sangria/issues/1068
WIP.
The main thing I'm missing is when checking that there's "exactly one non-null field" on a query (I have the `ExactlyOneOfFieldGiven` rule), I'm struggling with validating against `ast.VariableValue` (since I need the unmarshalled input for that). (and considering default values for `VariableDefinition` -- though that seems easier than getting the actual input)
was wondering if it needs to go in the execution part for checking variables, but that seems a bit messier.
Trying to figure it out...but feel free to contribute if you have a way to go about that
=> Support oneOf directive on input objects

modules/core/src/main/scala/sangria/renderer/QueryRenderer.scala, modules/core/src/main/scala/sangria/util/StringUtil.scala, modules/core/src/test/scala/sangria/renderer/QueryRendererSpec.scala
=> Fix: Schema rendering problems with Windows line separators

modules/core/src/main/scala/sangria/schema/package.scala, modules/core/src/test/scala/sangria/schema/CoercionSpec.scala
Solves: https://github.com/sangria-graphql/sangria/issues/1162
Let me know if this is really something that should be solved in `sangria-circe` instead?
=> Allow string inputs for Long Scalar type

build.sbt, modules/derivation/src/main/scala-3/sangria/macros/derive/DeriveMacroSupport.scala, modules/derivation/src/main/scala-3/sangria/macros/derive/DeriveObjectTypeMacro.scala, modules/derivation/src/test/scala/sangria/macros/derive/DeriveObjectTypeMacroSpec.scala, modules/derivation/src/test/scala/sangria/macros/derive/Issue906Context.scala
The actual change that fixes the issue is very simple, instead of summoning `[fieldType => Action[Ctx, fieldType]]` we summon `[fieldType => Action[Ctx, _]]`, so that we can also summon `ReduceAcrion.futureAction` and `tryAction` (previously we mistakenly limited ourselves to `defaultAction`).
I also allowed myself to simplify the code a bit, wrapping all of the faux-implicit conversions into a separate method, for readability.
Based on the minimization and research done in https://github.com/sangria-graphql/sangria/pull/1168 (I moved the test into the `DeriveObjectTypeMacroSuite`)
Fixes  #906
=> Fix issue with wrong Action[Ctx, _] conversion being summoned

modules/parser/src/main/scala/sangria/parser/PositionTracking.scala
Immutable array appends require an array copy. So memory allocations here grow quadratically with the number of lines in a schema file.
Large repos with a large graphql schemas can have thousands of lines which makes this significant.  
Switch Array -> Mutable ArrayBuffer
Also switches from linear search to binary search
On a 300k GraphQL schema from our production environment that cut parsing time from 16 seconds down to 3 seconds with position tracking and comment parsing.
(Test is not included because I don't have the time to anonymize it, sorry)
=> Fix O(N^2) memory allocation for parsing newlines
